### ISSUE TITLE
jsondecode error on array of empty object(s)

### ISSUE THREAD

**Issue by mtmiller** [apjanke/octave-jsonstuff#9]
Attempting to decode an array of one or more empty objects:

```
>> jsondecode ('[{}]')
error: =: nonconformant arguments (op1 is 1x1, op2 is 0x0)
error: called from
    jsondecode at line 36 column 7
>> jsondecode ('[{}, {}]')
error: =: nonconformant arguments (op1 is 1x1, op2 is 0x0)
error: called from
    jsondecode at line 36 column 7
```

The first should return the same as `jsondecode('{}')` or `struct()`, the second should return a 2×1 struct array with no fields, same as `resize(struct(), 2, 1)`.

**Comment by apjanke** [comment]
Thanks for the report!

I'm going to have to look at this tomorrow; I'm getting tired for the day.

**Comment by apjanke** [comment]
Argh, that "noncomformant arguments" is coming from inside the oct-file, and is raised by something in Octave, not jsonstuff's own oct-code. I can't figure out where it's coming from.

```
>> __jsonstuff_jsondecode_oct__ ('[{}]')
error: __jsonstuff_jsondecode_oct__: =: nonconformant arguments (op1 is 1x1, op2 is 0x0)
```

At least it says "=", so it's an assignment operation that's failing. I don't do much assignment, and this is a short case, so I'll just walk through it in my head.

Maybe it's [this assignment in `decode_array`](https://github.com/apjanke/octave-jsonstuff/blob/97a415a0ede7a69d3ba3d4db0635ce5adc3d6872/src/__jsonstuff_jsondecode_oct__.cc#L106):
```
Cell children (dim_vector (n_children, 1));
[...]
children(i) = rslt.value;
```

**Comment by apjanke** [comment]
Ah. I think it's [this assignment here](https://github.com/apjanke/octave-jsonstuff/issues/9):
```
s.assign (idx_vector (i), children(i).map_value ());
```
I determined that by just sticking in a bunch of `fprintf`s to see how far it got.

**Comment by apjanke** [comment]
Based on the expected values reported by @mtmiller, I think it's the case that 0-field structs are not considered candidates for condensation. (I don't know why that would be, but let's go with it.)

Looks like the error is raised because 0-field JSON objects are getting converted to empty 0-field structs instead of scalar 0-field structs. I'll need to look in to the behavior of `octave_map` and `octave_value (octave_map)` to figure that one out. At any rate, the assignment error is avoided, and less-wrong results are produced, if we just consider 0-field structs to not be candidates for condensation. Done here: https://github.com/apjanke/octave-jsonstuff/commit/55ee6b478f02983637ea81dff26c94ff85402b64

That gets us:
```
>> jsondecode ('[{}]')
ans =
{
  [1,1] =
    0x0 struct array containing the fields:

}

>> jsondecode ('[{},{}]')
ans =
{
  [1,1] =
    0x0 struct array containing the fields:

  [2,1] =
    0x0 struct array containing the fields:

}

>> jsondecode ('{}')
ans =
  0x0 struct array containing the fields:
```

This is still wrong. All those JSON `{}` objects should be turning into scalar 0-field structs, not empty 0-field structs.

**Comment by apjanke** [comment]
Does anyone know how to create a scalar (not empty 0-by-0) struct in C++ oct-file code?

**Comment by apjanke** [comment]
Aha! Use `octave_scalar_map` instead of `octave_map`. Fixed in https://github.com/apjanke/octave-jsonstuff/commit/fe17299c78644beb8ba026baa47f5329f6c6ac32.

This case is working now, I think.

```
>> jsondecode ('{}')
ans =
  scalar structure containing the fields:

>> jsondecode ('[{}]')
ans =
{
  [1,1] =
    scalar structure containing the fields:
}

>> jsondecode ('[{}, {}]')
ans =
{
  [1,1] =
    scalar structure containing the fields:
  [2,1] =
    scalar structure containing the fields:
}

>>
```

Closing as fixed.

**Comment by apjanke** [comment]
Wait, no, this isn't fixed. That scalar struct should not be embedded in a cell array. Re-opening.

**Comment by apjanke** [comment]
Crap. I think part of the issue here is that, just like numerics, sticking arrays of JSON objects inside multiple levels of `[...]` arrays causes them to be permuted into higher dimensions.

I think the thing to do might be to pull most of the condensation logic out into the M-code layer until we get the algorithm right, and then push it back down into the oct-file C++ code as an optimization.

**Comment by apjanke** [comment]
Fixed by pulling the condensation logic up in to the M-code layer for now. https://github.com/apjanke/octave-jsonstuff/issues/10.

I've got all the cases mentioned here passing. Let me know if you see others going wrong.
